# Set up your streams to rtsp here.
port: "8554"
streams: # Cannot rename - must leave this as is.

  stream-auip:
    type: topic
    source: /auip/rtsp/image
    mountpoint: /auip
    caps: video/x-raw,framerate=10/1,width=1224,height=1024
    bitrate: 5000

